<a href="https://colab.research.google.com/github/natdebandi/hate_speech_ar/blob/main/4_analysis_hate_ar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Analisis del Dataset completo marzo 2020 - abril 2021 de X

**Natalia Dedandi**

Se aplica el clasificador seleccionado a todo el conjunto de datos recoelctado para analizar las características del odio en Argentina durante la pandemia

In [1]:
!pip install datasets seaborn

Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (2.20.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.1.4)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.5)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.5.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2024.5.0,>=2023.1.0->datasets) (2024.5.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.1)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.10/dist-packages (from seaborn) (3.7.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.3.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

Recupero el conjutno completo de datos: https://huggingface.co/datasets/piuba-bigdata/articles_and_comments

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset("piubamas/articles_and_comments")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['tweet_id', 'text', 'title', 'url', 'user', 'body', 'created_at', 'comments'],
        num_rows: 537201
    })
})

In [4]:
ds1 = dataset["train"]

Ejemplo de una fila

In [5]:
ds1[122]

{'tweet_id': '1376979520729849858',
 'text': 'Una fuerte apuesta a la rueda de la agroindustrialización argentina https://t.co/1o6ThCdtxw https://t.co/TLfGhLBjHu',
 'title': 'Una fuerte apuesta a la rueda de la agroindustrialización argentina',
 'url': 'https://www.lanacion.com.ar/economia/campo/una-fuerte-apuesta-a-la-rueda-de-la-agroindustrializacion-argentina-nid30032021/?utm_term=Autofeed&utm_medium=Echobox&utm_source=Twitter#Echobox=1617130198',
 'user': 'LANACION',
 'body': 'Desde el primer día, YPF Agro se propuso proveer al campo argentino de los insumos y las energías necesarias para producir más y mejor, en un contexto donde la demanda de alimentos para la población mundial sigue creciendo.\n\nEl negocio de agro de YPF cerró 2020 con ventas mayores a 1.428 millones de dólares y más de 1,5 millones de toneladas de grano canjeadas, y apuesta a incrementar estos resultados en 2021.\n\nEn ese sentido, lanzó su nueva campaña de comunicación orientada a reforzar la idea de circularidad de la actividad agrícola, después del relanzamiento de la marca en 2019.\n\nDe esta manera, la división Agro de la petrolera nacional continúa desafiando al mercado con su nuevo posicionamiento a través de soluciones integrales e innovadoras y acompaña al campo argentino en cada momento del ciclo productivo.\n\nLa producción agroindustrial alcanza a todos los lugares en todos momentos y eso es lo que transmite el nuevo comercial de YPF Agro que se suma en cualquier punto del ciclo para acompañar este proceso de producción.\n\nEn este punto, el foco está puesto en resaltar la gama de productos que la compañía tiene para ofrecer al mercado argentino:\n\nProtección de cultivos: YPF Agro refuerza la importancia del cuidado de los cultivos y destaca su atributo de calidad en fitosanitarios para dar solución a las distintas problemáticas de acuerdo con las regiones y cultivos.\n\nYPF Agro refuerza la importancia del cuidado de los cultivos y destaca su atributo de calidad en fitosanitarios para dar solución a las distintas problemáticas de acuerdo con las regiones y cultivos. Portfolio Semillas: A partir de la alianza estratégica con la marca ILLINOIS de probada trayectoria, competitividad y calidad, la tecnología disponible en semillas de YPF para todo el país se refuerza.\n\nA partir de la alianza estratégica con la marca ILLINOIS de probada trayectoria, competitividad y calidad, la tecnología disponible en semillas de YPF para todo el país se refuerza. Nutrición integral: El servicio de nutrición integral potencia el rinde con Summa Mix, una marca desarrollada para implementar mezclas a medida que se ajusten a la necesidad de cada ambiente productivo.\n\nEl servicio de nutrición integral potencia el rinde con Summa Mix, una marca desarrollada para implementar mezclas a medida que se ajusten a la necesidad de cada ambiente productivo. Sustento & Energía: Refuerza la trayectoria de la marca en combustibles y lubricantes de máxima calidad con un diferencial de llegada a la tranquera en todo el país. Esto permite poner en movimiento el ciclo de cada campaña agrícola y potenciar el rinde del cultivo.\n\nYPF Agro se consolida como referente en la industria Twitter\n\nYPF Agro, veinte años de trayectoria\n\nCon más de 20 años de experiencia, YPF Agro sigue transformando el trabajo del agricultor argentino y asegura su presencia en todo el país con más de 100 centros de distribución.\n\nAdemás de los cuatro pilares de su portfolio, YPF Agro provee bolsas silo para el almacenaje de granos, el canje de granos como herramienta de pago y servicios de asesoramiento integral.\n\nNuevo canje de granos para la cosecha gruesa\n\nPara acompañar este lanzamiento, cercano al inicio de la cosecha gruesa, YPF Agro lanza una nueva edición de su exitoso canje de granos.\n\nLos productores podrán canjear sus granos de soja y maíz recibiendo un plus de hasta 14 dólares por tonelada y acceder con grandes beneficios a la compra de insumos en protección, nutrición y combustibles. Para más información pueden visitar el sitio de YPF Agro.\n\nDe este modo, YPF Agro se consolida como referente en la industria y contribuye con el desarrollo del sector.\n\n________________________________________________________\n\nContent LAB es la unidad de generación de ideas y contenidos de LA NACION para las marcas con distribución en sus plataformas digitales y redes sociales. Este contenido fue producido para un anunciante y publicado por el Content LAB. La redacción de LA NACION no estuvo involucrada en la generación de este contenido.',
 'created_at': '2021-03-30T19:27:55Z',
 'comments': [{'created_at': '2021-03-30T21:24:03Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@LANACION basta de agroquimicos ! el futuro es la alimentation organica y el respeto de la naturaleza',
   'tweet_id': '1377008748242345986',
   'user_id': '2366473882'},
  {'created_at': '2021-03-30T23:14:41Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@LANACION Buenas Tardes.e dejado Notificaciones de mis denuncias .y los medios me https://t.co/l6B7tyVVV3 voy a permitir más k me amenazan cn mi pobre vida y https://t.co/Wws6czclV9 la dueña..Nadie puede ha ser política cn mis derechos.',
   'tweet_id': '1377036587750547456',
   'user_id': '1374092858228142081'}]}

En este conjunto de datos tengo las etiquetas de la clasificación realizada con el modelo BETO:

https://huggingface.co/piuba-bigdata/beto-contextualized-hate-speech

Puede usarse para comparar pero en principio nos interesa recuperar los comentarios completos para aplicarle el clasificador seleccionado

In [6]:
from datetime import datetime, timedelta
from tqdm.auto import tqdm
from collections import Counter

In [13]:
tweets_arg = []

for noticia in tqdm(dataset['train']):

    date_noticia = noticia["created_at"]
    # Convertimos la fecha de la noticia a un objeto de python
    datenoticia = datetime.strptime(date_noticia, "%Y-%m-%dT%H:%M:%S%fZ")
    i=0
    for comment in noticia["comments"]:
        date_comment = comment["created_at"]
        # Convertimos la fecha del comentario a un objeto de python
        datecomment = datetime.strptime(date_comment, "%Y-%m-%dT%H:%M:%S%fZ")
        # anexa comentarios de diarios argentinos
        tweets_arg.append({"id":i,
            "tweet_id_noticia": noticia["tweet_id"],
            "date_tweet": datecomment,
            "text": comment["text"],
            "CALLS":comment["prediction"]["CALLS"],
            "WOMEN":comment["prediction"]["WOMEN"],
            "LGBTI":comment["prediction"]["LGBTI"],
            "RACISM":comment["prediction"]["RACISM"],
            "CLASS":comment["prediction"]["CLASS"],
            "POLITICS":comment["prediction"]["POLITICS"],
            "DISABLED":comment["prediction"]["DISABLED"],
            "APPEARANCE":comment["prediction"]["APPEARANCE"],
            "CRIMINAL":comment["prediction"]["CRIMINAL"]
            })
        i=i+1

  0%|          | 0/537201 [00:00<?, ?it/s]

In [15]:
tweets_arg[11]

{'id': 3,
 'tweet_id_noticia': '1376940852011020288',
 'date_tweet': datetime.datetime(2021, 3, 30, 17, 49, 1, 500000),
 'text': '@LANACION Re largo el sueño',
 'CALLS': 0,
 'WOMEN': 0,
 'LGBTI': 0,
 'RACISM': 0,
 'CLASS': 0,
 'POLITICS': 0,
 'DISABLED': 0,
 'APPEARANCE': 0,
 'CRIMINAL': 0}

In [16]:
# prompt: create a dataframe from tweets_arg

df_tweets_arg = pd.DataFrame(tweets_arg)

In [19]:
df_tweets_arg['HATEFUL']= df_tweets_arg[['CALLS','WOMEN','LGBTI','RACISM','CLASS','POLITICS','DISABLED','APPEARANCE','CRIMINAL']].max(axis=1)

In [20]:
df_tweets_arg.head()

,id,tweet_id_noticia,date_tweet,text,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL,HATEFUL
0,0,1376940813968609288,2021-03-30 17:03:00.900,@clarincom A mi me preocupa el trabajo.. La ev...,0,0,0,0,0,0,0,0,0,0
1,1,1376940813968609288,2021-03-30 17:05:04.500,@clarincom Lo que preocupa. https://t.co/Vmf9V...,0,0,0,0,0,0,0,0,0,0
2,2,1376940813968609288,2021-03-30 17:06:03.100,@clarincom Lo que les preocupa. https://t.co/P...,0,0,0,0,0,0,0,0,0,0
3,3,1376940813968609288,2021-03-30 17:11:02.300,@clarincom Le recomendaríamos al presidente de...,0,0,0,0,0,0,0,0,0,0
4,4,1376940813968609288,2021-03-30 17:26:00.600,@clarincom Para salvar al correo de la quiebra...,0,0,0,0,0,0,0,0,0,0

coloco el mismo orden de las etiquetas que usa el clasificador

In [21]:
# prompt: change the order of columns of df_tweets_arg and put HATEFUL before CALLS

df_tweets_arg = df_tweets_arg[['id', 'tweet_id_noticia', 'date_tweet', 'text', 'HATEFUL', 'CALLS', 'WOMEN',
       'LGBTI', 'RACISM', 'CLASS', 'POLITICS', 'DISABLED', 'APPEARANCE',
       'CRIMINAL']]
df_tweets_arg.head()

,id,tweet_id_noticia,date_tweet,text,HATEFUL,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL
0,0,1376940813968609288,2021-03-30 17:03:00.900,@clarincom A mi me preocupa el trabajo.. La ev...,0,0,0,0,0,0,0,0,0,0
1,1,1376940813968609288,2021-03-30 17:05:04.500,@clarincom Lo que preocupa. https://t.co/Vmf9V...,0,0,0,0,0,0,0,0,0,0
2,2,1376940813968609288,2021-03-30 17:06:03.100,@clarincom Lo que les preocupa. https://t.co/P...,0,0,0,0,0,0,0,0,0,0
3,3,1376940813968609288,2021-03-30 17:11:02.300,@clarincom Le recomendaríamos al presidente de...,0,0,0,0,0,0,0,0,0,0
4,4,1376940813968609288,2021-03-30 17:26:00.600,@clarincom Para salvar al correo de la quiebra...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# prompt: save df_tweets_arg to csv file

df_tweets_arg.to_csv('data/tweets_arg.csv', index=False)

In [40]:
# prompt: len of df_tweets_arg

len(df_tweets_arg)

8569648