<a href="https://colab.research.google.com/github/natdebandi/hate_speech_ar/blob/main/4_analysis_hate_ar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Analisis del Dataset completo marzo 2020 - abril 2021 de X

**Natalia Dedandi**

Se aplica el clasificador seleccionado a todo el conjunto de datos recoelctado para analizar las características del odio en Argentina durante la pandemia

In [1]:
%pip install datasets seaborn

Collecting datasets
  Downloading datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: seaborn in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Collecting filelock (from datasets)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from datasets) (2.4.2)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from datasets) (3.0.1)
Collecting requests>=2.32.2 (from datasets)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1.0.0 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from datasets) (4.67.3)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.7.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\natal\appdata\roaming\python\python312\site-packages (from datasets) (26.0)
Collecting pyyaml>=5.1 (from datasets)
  Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.10.8)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp312-cp312-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\natal\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from pandas->datasets) (2025.3)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.32.2->datasets)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: colorama in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp312-cp312-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: six>=1.5 in c:\users\natal\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\natal\appdata\roaming\python\python312\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ---------------------------------------- 527.0/527.0 kB 8.3 MB/s eta 0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading huggingface_hub-1.7.2-py3-none-any.whl (618 kB)
   ---------------------------------------- 0.0/618.0 kB ? eta -:--:--
   --------------------------------------- 618.0/618.0 kB 11.5 MB/s eta 0:00:00
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ------- -------------------------------- 5.5/27.6 MB 30.5 MB/s eta 0:00:01
   ----------------- ---------------------- 11.8/27.6 MB 29.5 MB/s eta 0:00:01
   ----------------------- ---------------- 16.0/27.6 MB 25.8 MB/s eta 0:00:01
   ------------------------------- -------- 21.5/27.6 MB 25.6 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.6 MB 26.8 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 24.6 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading xxhash-3.6.0-cp312-cp312-win_amd64.whl (31 kB)
Downloading aiohttp-3.13.3-cp312-cp312-win_amd64.whl (455 kB)
Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl (154 kB)
Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ---------------------------------------- 3.7/3.7 MB 27.3 MB/s eta 0:00:00
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Downloading multidict-6.7.1-cp312-cp312-win_amd64.whl (46 kB)
Downloading propcache-0.4.1-cp312-cp312-win_amd64.whl (41 kB)
Downloading rich-14.3.3-py3-none-any.whl (310 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading yarl-1.23.0-cp312-cp312-win_amd64.whl (87 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: xxhash, urllib3, shellingham, pyyaml, pyarrow, propcache, multidict, mdurl, hf-xet, fsspec, frozenlist, filelock, dill, charset_normalizer, annotated-doc, aiohappyeyeballs, yarl, requests, multiprocess, markdown-it-py, aiosignal, rich, aiohttp, typer, huggingface-hub, datasets
Successfully installed aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 annotated-doc-0.0.4 charset_normalizer-3.4.6 datasets-4.8.4 dill-0.4.1 filelock-3.25.2 frozenlist-1.8.0 fsspec-2026.2.0 hf-xet-1.4.2 huggingface-hub-1.7.2 markdown-it-py-4.0.0 mdurl-0.1.2 multidict-6.7.1 multiprocess-0.70.19 propcache-0.4.1 pyarrow-23.0.1 pyyaml-6.0.3 requests-2.32.5 rich-14.3.3 shellingham-1.5.4 typer-0.24.1 urllib3-2.6.3 xxhash-3.6.0 yarl-1.23.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install pandas
%pip install seaborn

Requirement already satisfied: pandas in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\natal\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\natal\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\natal\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\natal\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\natal\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Recupero el conjutno completo de datos: https://huggingface.co/datasets/piuba-bigdata/articles_and_comments

In [3]:
%pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Requirement already satisfied: python-dotenv in c:\users\natal\appdata\local\programs\python\python312\lib\site-packages (from dotenv) (1.2.1)
Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: dotenv
Successfully installed dotenv-0.9.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import os
from dotenv import load_dotenv
from datasets import load_dataset
import pandas as pd

load_dotenv() 
token = os.getenv("HF_TOKEN")


dataset = load_dataset("piubamas/articles_and_comments", token=token)

c:\Users\natal\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\natal\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\natal\.cache\huggingface\hub\datasets--piubamas--articles_and_comments. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Generating train split: 100%|██████████| 537201/537201 [00:52<00:00, 10313.19 examples/s]

In [5]:
#from datasets import load_dataset
#import pandas as pd

#dataset = load_dataset("piubamas/articles_and_comments")

In [6]:
dataset

DatasetDict({
    train: Dataset({
        features: ['tweet_id', 'text', 'title', 'url', 'user', 'body', 'created_at', 'comments'],
        num_rows: 537201
    })
})

In [7]:
ds1 = dataset["train"]

Ejemplo de una fila

In [9]:
ds1[354]

{'tweet_id': '1377046872343392256',
 'text': 'Lawfare, el día después https://t.co/QDZnv0QbX4',
 'title': None,
 'url': None,
 'user': 'pagina12',
 'body': None,
 'created_at': '2021-03-30T23:55:33Z',
 'comments': [{'created_at': '2021-03-30T23:58:03Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 https://t.co/LfVPBEvLR0',
   'tweet_id': '1377047501866405893',
   'user_id': '89962248'},
  {'created_at': '2021-03-30T23:58:43Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 Y dale con temas que a nadie importa, salvo a la mechera. Mientras tanto los precios al galope. Inútiles',
   'tweet_id': '1377047670540398592',
   'user_id': '1349538511670673408'},
  {'created_at': '2021-03-30T23:58:50Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 https://t.co/2k5EZT46x1',
   'tweet_id': '1377047698914836481',
   'user_id': '715349270208114688'},
  {'created_at': '2021-03-30T23:59:36Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 https://t.co/FqZ7obXrGQ',
   'tweet_id': '1377047890275745792',
   'user_id': '907735084828123136'},
  {'created_at': '2021-03-31T00:00:47Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 Si realmente existiera el LawFare, La Araña estaría talando árboles en el Parque Nacional de Tierra del Fuego, descalza y entangada',
   'tweet_id': '1377048191653326849',
   'user_id': '1271778395110637570'},
  {'created_at': '2021-03-31T00:03:02Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 A esa cara le va frase de su autoria "les puedo hacer mucho daño".\n\nY logro ese logro.',
   'tweet_id': '1377048756546367491',
   'user_id': '183896225'},
  {'created_at': '2021-03-31T00:18:48Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 1},
   'text': '@pagina12 Gato gato gato gato.eso SOS vos macri delincuente chorro parece q esa palabras fueron hechas inventadas para vos gato macri pq son justo lo q sos vos gato.ya ningún juez te va poder defender ningún amiguito tuyo te va defender vas a la cárcel no te salvas',
   'tweet_id': '1377052724320161799',
   'user_id': '1353813659076734977'},
  {'created_at': '2021-03-31T00:53:46Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@pagina12 Para los kachorros todo es lawfare',
   'tweet_id': '1377061521898016768',
   'user_id': '1365848759884800000'}]}

En este conjunto de datos tengo las etiquetas de la clasificación realizada con el modelo BETO:

https://huggingface.co/piuba-bigdata/beto-contextualized-hate-speech

Puede usarse para comparar pero en principio nos interesa recuperar los comentarios completos para aplicarle el clasificador seleccionado

In [10]:
from datetime import datetime, timedelta
from tqdm.auto import tqdm
from collections import Counter

In [11]:
tweets_arg = []

for noticia in tqdm(dataset['train']):

    date_noticia = noticia["created_at"]
    # Convertimos la fecha de la noticia a un objeto de python
    datenoticia = datetime.strptime(date_noticia, "%Y-%m-%dT%H:%M:%S%fZ")
    i=0
    for comment in noticia["comments"]:
        date_comment = comment["created_at"]
        # Convertimos la fecha del comentario a un objeto de python
        datecomment = datetime.strptime(date_comment, "%Y-%m-%dT%H:%M:%S%fZ")
        # anexa comentarios de diarios argentinos
        tweets_arg.append({"id":i,
            "tweet_id_noticia": noticia["tweet_id"],
            "title": noticia["title"],
            "resumen": noticia["text"],
            "medio": noticia["user"],
            "date_tweet": datecomment,
            "text": comment["text"],
            "user_id": comment["user_id"],
            "CALLS":comment["prediction"]["CALLS"],
            "WOMEN":comment["prediction"]["WOMEN"],
            "LGBTI":comment["prediction"]["LGBTI"],
            "RACISM":comment["prediction"]["RACISM"],
            "CLASS":comment["prediction"]["CLASS"],
            "POLITICS":comment["prediction"]["POLITICS"],
            "DISABLED":comment["prediction"]["DISABLED"],
            "APPEARANCE":comment["prediction"]["APPEARANCE"],
            "CRIMINAL":comment["prediction"]["CRIMINAL"]
            })
        i=i+1

100%|██████████| 537201/537201 [08:04<00:00, 1109.35it/s]

In [13]:
tweets_arg[1156]

{'id': 150,
 'tweet_id_noticia': '1376946868161220610',
 'title': 'Polémica: un proyecto K propone multas millonarias y endurecer penas de prisión para el que propague el Covid',
 'resumen': 'Polémica: un proyecto K propone multas millonarias y endurecer penas de prisión para el que propague el Covid https://t.co/snNm3UBvmR',
 'medio': 'clarincom',
 'date_tweet': datetime.datetime(2021, 3, 30, 18, 9, 0, 800000),
 'text': '@clarincom Cómo en el funeral que organizaron del Diego. O las marchas y contramarchas del aborto',
 'user_id': '882377587',
 'CALLS': 0,
 'WOMEN': 0,
 'LGBTI': 0,
 'RACISM': 0,
 'CLASS': 0,
 'POLITICS': 0,
 'DISABLED': 0,
 'APPEARANCE': 0,
 'CRIMINAL': 0}

In [14]:
# prompt: create a dataframe from tweets_arg

df_tweets_arg = pd.DataFrame(tweets_arg)

In [15]:
df_tweets_arg['HATEFUL']= df_tweets_arg[['CALLS','WOMEN','LGBTI','RACISM','CLASS','POLITICS','DISABLED','APPEARANCE','CRIMINAL']].max(axis=1)

In [16]:
df_tweets_arg.head()

,id,tweet_id_noticia,title,resumen,medio,date_tweet,text,user_id,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL,HATEFUL
0,0,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:03:00.900,@clarincom A mi me preocupa el trabajo.. La ev...,1532596098,0,0,0,0,0,0,0,0,0,0
1,1,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:05:04.500,@clarincom Lo que preocupa. https://t.co/Vmf9V...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
2,2,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:06:03.100,@clarincom Lo que les preocupa. https://t.co/P...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
3,3,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:11:02.300,@clarincom Le recomendaríamos al presidente de...,582286194,0,0,0,0,0,0,0,0,0,0
4,4,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:26:00.600,@clarincom Para salvar al correo de la quiebra...,951552761988034560,0,0,0,0,0,0,0,0,0,0

coloco el mismo orden de las etiquetas que usa el clasificador

In [17]:
# prompt: change the order of columns of df_tweets_arg and put HATEFUL before CALLS


df_tweets_arg = df_tweets_arg[['id', 'tweet_id_noticia','title','resumen','medio', 'date_tweet', 'text', 'user_id', 'HATEFUL', 'CALLS', 'WOMEN',
       'LGBTI', 'RACISM', 'CLASS', 'POLITICS', 'DISABLED', 'APPEARANCE',
       'CRIMINAL']]
df_tweets_arg.head()

,id,tweet_id_noticia,title,resumen,medio,date_tweet,text,user_id,HATEFUL,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL
0,0,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:03:00.900,@clarincom A mi me preocupa el trabajo.. La ev...,1532596098,0,0,0,0,0,0,0,0,0,0
1,1,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:05:04.500,@clarincom Lo que preocupa. https://t.co/Vmf9V...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
2,2,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:06:03.100,@clarincom Lo que les preocupa. https://t.co/P...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
3,3,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:11:02.300,@clarincom Le recomendaríamos al presidente de...,582286194,0,0,0,0,0,0,0,0,0,0
4,4,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:26:00.600,@clarincom Para salvar al correo de la quiebra...,951552761988034560,0,0,0,0,0,0,0,0,0,0

In [18]:
# prompt: save df_tweets_arg to csv file

df_tweets_arg.to_csv('data/tweets_con_noticia.csv', index=False)

In [17]:
# prompt: len of df_tweets_arg

len(df_tweets_arg)

8569648