<a href="https://colab.research.google.com/github/natdebandi/hate_speech_ar/blob/main/4_analysis_hate_ar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Analisis del Dataset completo marzo 2020 - abril 2021 de X

**Natalia Dedandi**

Se aplica el clasificador seleccionado a todo el conjunto de datos recoelctado para analizar las características del odio en Argentina durante la pandemia

In [1]:
%pip install datasets seaborn

Collecting datasets
  Downloading datasets-4.8.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: seaborn in c:\users\usuario\ciai\venv\lib\site-packages (0.13.2)
Collecting filelock (from datasets)
  Downloading filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (2.4.3)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-23.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (3.0.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (4.67.3)
Collecting xxhash (from datasets)
  Downloading xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Downloading multiprocess-0.70.19-py311-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Downloading huggingface_hub-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\usuario\ciai\venv\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\usuario\ciai\venv\lib\site-packages (from seaborn) (3.10.8)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: anyio in c:\users\usuario\ciai\venv\lib\site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in c:\users\usuario\ciai\venv\lib\site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\usuario\ciai\venv\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\usuario\ciai\venv\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\usuario\ciai\venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: typer in c:\users\usuario\ciai\venv\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\usuario\ciai\venv\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: pillow>=8 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\usuario\ciai\venv\lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\usuario\ciai\venv\lib\site-packages (from requests>=2.32.2->datasets) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\usuario\ciai\venv\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: colorama in c:\users\usuario\ciai\venv\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\usuario\ciai\venv\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
     ---------------------------------------- 0.0/82.2 kB ? eta -:--:--
     -------------- ------------------------- 30.7/82.2 kB 1.4 MB/s eta 0:00:01
     -------------------------------------- 82.2/82.2 kB 922.5 kB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\usuario\ciai\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: click>=8.2.1 in c:\users\usuario\ciai\venv\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\usuario\ciai\venv\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\usuario\ciai\venv\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\usuario\ciai\venv\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\usuario\ciai\venv\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\usuario\ciai\venv\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\usuario\ciai\venv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Downloading datasets-4.8.2-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/526.6 kB ? eta -:--:--
    --------------------------------------- 10.2/526.6 kB ? eta -:--:--
   --- ----------------------------------- 41.0/526.6 kB 487.6 kB/s eta 0:00:01
   ---- ---------------------------------- 61.4/526.6 kB 465.5 kB/s eta 0:00:01
   ------ -------------------------------- 81.9/526.6 kB 456.6 kB/s eta 0:00:01
   ------ -------------------------------- 81.9/526.6 kB 456.6 kB/s eta 0:00:01
   ------ -------------------------------- 92.2/526.6 kB 348.6 kB/s eta 0:00:02
   -------- ----------------------------- 112.6/526.6 kB 363.1 kB/s eta 0:00:02
   -------- ----------------------------- 122.9/526.6 kB 343.4 kB/s eta 0:00:02
   ---------- --------------------------- 143.4/526.6 kB 369.8 kB/s eta 0:00:02
   ----------- -------------------------- 163.8/526.6 kB 392.8 kB/s eta 0:00:01
   ------------ ------------------------- 174.1/526.6 kB 361.7 kB/s eta 0:00:01
   -------------- ----------------------- 194.6/526.6 kB 380.0 kB/s eta 0:00:01
   ---------------- --------------------- 225.3/526.6 kB 393.1 kB/s eta 0:00:01
   ---------------- --------------------- 225.3/526.6 kB 393.1 kB/s eta 0:00:01
   ----------------- -------------------- 245.8/526.6 kB 386.1 kB/s eta 0:00:01
   ------------------ ------------------- 256.0/526.6 kB 383.4 kB/s eta 0:00:01
   ------------------- ------------------ 276.5/526.6 kB 387.0 kB/s eta 0:00:01
   ---------------------- --------------- 307.2/526.6 kB 387.7 kB/s eta 0:00:01
   ---------------------- --------------- 307.2/526.6 kB 387.7 kB/s eta 0:00:01
   ------------------------ ------------- 337.9/526.6 kB 388.2 kB/s eta 0:00:01
   ------------------------- ------------ 358.4/526.6 kB 390.8 kB/s eta 0:00:01
   ---------------------------- --------- 389.1/526.6 kB 403.9 kB/s eta 0:00:01
   ----------------------------- -------- 409.6/526.6 kB 412.1 kB/s eta 0:00:01
   ----------------------------- -------- 409.6/526.6 kB 412.1 kB/s eta 0:00:01
   ------------------------------- ------ 440.3/526.6 kB 404.6 kB/s eta 0:00:01
   -------------------------------- ----- 450.6/526.6 kB 408.5 kB/s eta 0:00:01
   ----------------------------------- -- 491.5/526.6 kB 410.6 kB/s eta 0:00:01
   ----------------------------------- -- 491.5/526.6 kB 410.6 kB/s eta 0:00:01
   -------------------------------------  522.2/526.6 kB 409.6 kB/s eta 0:00:01
   -------------------------------------- 526.6/526.6 kB 402.8 kB/s eta 0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
   ---------------------------------------- 0.0/120.0 kB ? eta -:--:--
   --- ------------------------------------ 10.2/120.0 kB ? eta -:--:--
   ------------------- ------------------- 61.4/120.0 kB 812.7 kB/s eta 0:00:01
   ----------------------------- --------- 92.2/120.0 kB 744.7 kB/s eta 0:00:01
   ----------------------------------- -- 112.6/120.0 kB 726.2 kB/s eta 0:00:01
   -------------------------------------- 120.0/120.0 kB 583.9 kB/s eta 0:00:00
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
   ---------------------------------------- 0.0/202.5 kB ? eta -:--:--
   -- ------------------------------------- 10.2/202.5 kB ? eta -:--:--
   ------- ------------------------------- 41.0/202.5 kB 653.6 kB/s eta 0:00:01
   ----------- --------------------------- 61.4/202.5 kB 825.8 kB/s eta 0:00:01
   ----------------- --------------------- 92.2/202.5 kB 585.1 kB/s eta 0:00:01
   --------------------- ---------------- 112.6/202.5 kB 595.3 kB/s eta 0:00:01
   ----------------------- -------------- 122.9/202.5 kB 554.9 kB/s eta 0:00:01
   -------------------------- ----------- 143.4/202.5 kB 532.5 kB/s eta 0:00:01
   ---------------------------- --------- 153.6/202.5 kB 482.7 kB/s eta 0:00:01
   ------------------------------------ - 194.6/202.5 kB 537.4 kB/s eta 0:00:01
   ------------------------------------ - 194.6/202.5 kB 537.4 kB/s eta 0:00:01
   -------------------------------------- 202.5/202.5 kB 455.6 kB/s eta 0:00:00
Downloading huggingface_hub-1.7.1-py3-none-any.whl (616 kB)
   ---------------------------------------- 0.0/616.3 kB ? eta -:--:--
   ---------------------------------------- 0.0/616.3 kB ? eta -:--:--
   - ------------------------------------- 30.7/616.3 kB 660.6 kB/s eta 0:00:01
   --- ----------------------------------- 61.4/616.3 kB 656.4 kB/s eta 0:00:01
   --- ----------------------------------- 61.4/616.3 kB 656.4 kB/s eta 0:00:01
   ----- --------------------------------- 81.9/616.3 kB 508.4 kB/s eta 0:00:02
   ------ ------------------------------- 112.6/616.3 kB 467.6 kB/s eta 0:00:02
   -------- ----------------------------- 143.4/616.3 kB 532.5 kB/s eta 0:00:01
   -------- ----------------------------- 143.4/616.3 kB 532.5 kB/s eta 0:00:01
   ---------- --------------------------- 174.1/616.3 kB 476.3 kB/s eta 0:00:01
   ------------- ------------------------ 225.3/616.3 kB 550.0 kB/s eta 0:00:01
   ------------- ------------------------ 225.3/616.3 kB 550.0 kB/s eta 0:00:01
   --------------- ---------------------- 245.8/616.3 kB 519.9 kB/s eta 0:00:01
   ----------------- -------------------- 286.7/616.3 kB 520.7 kB/s eta 0:00:01
   ------------------- ------------------ 317.4/616.3 kB 531.5 kB/s eta 0:00:01
   --------------------- ---------------- 348.2/616.3 kB 554.9 kB/s eta 0:00:01
   ---------------------- --------------- 368.6/616.3 kB 533.3 kB/s eta 0:00:01
   ----------------------- -------------- 378.9/616.3 kB 536.6 kB/s eta 0:00:01
   ------------------------ ------------- 399.4/616.3 kB 530.1 kB/s eta 0:00:01
   -------------------------- ----------- 430.1/616.3 kB 526.8 kB/s eta 0:00:01
   ---------------------------- --------- 460.8/616.3 kB 533.8 kB/s eta 0:00:01
   ------------------------------ ------- 491.5/616.3 kB 540.2 kB/s eta 0:00:01
   -------------------------------- ----- 522.2/616.3 kB 555.3 kB/s eta 0:00:01
   --------------------------------- ---- 542.7/616.3 kB 558.7 kB/s eta 0:00:01
   ----------------------------------- -- 573.4/616.3 kB 554.3 kB/s eta 0:00:01
   -------------------------------------  614.4/616.3 kB 568.9 kB/s eta 0:00:01
   -------------------------------------- 616.3/616.3 kB 546.5 kB/s eta 0:00:00
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Downloading multiprocess-0.70.19-py311-none-any.whl (144 kB)
   ---------------------------------------- 0.0/144.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/144.5 kB ? eta -:--:--
   -------- ------------------------------ 30.7/144.5 kB 640.0 kB/s eta 0:00:01
   ----------- --------------------------- 41.0/144.5 kB 487.6 kB/s eta 0:00:01
   ---------------------- ---------------- 81.9/144.5 kB 573.4 kB/s eta 0:00:01
   ------------------------ -------------- 92.2/144.5 kB 521.8 kB/s eta 0:00:01
   -------------------------------- ----- 122.9/144.5 kB 514.3 kB/s eta 0:00:01
   -------------------------------------  143.4/144.5 kB 532.5 kB/s eta 0:00:01
   -------------------------------------- 144.5/144.5 kB 475.9 kB/s eta 0:00:00
Downloading pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.5 MB 1.3 MB/s eta 0:00:22
   ---------------------------------------- 0.1/27.5 MB 812.7 kB/s eta 0:00:34
   ---------------------------------------- 0.1/27.5 MB 651.6 kB/s eta 0:00:43
   ---------------------------------------- 0.1/27.5 MB 652.2 kB/s eta 0:00:43
   ---------------------------------------- 0.1/27.5 MB 599.1 kB/s eta 0:00:46
   ---------------------------------------- 0.1/27.5 MB 607.9 kB/s eta 0:00:46
   ---------------------------------------- 0.2/27.5 MB 551.6 kB/s eta 0:00:50
   ---------------------------------------- 0.2/27.5 MB 540.4 kB/s eta 0:00:51
   ---------------------------------------- 0.2/27.5 MB 578.7 kB/s eta 0:00:48
   ---------------------------------------- 0.3/27.5 MB 561.1 kB/s eta 0:00:49
   ---------------------------------------- 0.3/27.5 MB 553.0 kB/s eta 0:00:50
   ---------------------------------------- 0.3/27.5 MB 558.2 kB/s eta 0:00:49
   ---------------------------------------- 0.3/27.5 MB 563.8 kB/s eta 0:00:49
    --------------------------------------- 0.4/27.5 MB 543.2 kB/s eta 0:00:51
    --------------------------------------- 0.4/27.5 MB 563.8 kB/s eta 0:00:49
    --------------------------------------- 0.4/27.5 MB 569.7 kB/s eta 0:00:48
    --------------------------------------- 0.5/27.5 MB 574.8 kB/s eta 0:00:48
    --------------------------------------- 0.5/27.5 MB 604.6 kB/s eta 0:00:45
    --------------------------------------- 0.5/27.5 MB 618.8 kB/s eta 0:00:44
    --------------------------------------- 0.6/27.5 MB 620.9 kB/s eta 0:00:44
    --------------------------------------- 0.6/27.5 MB 611.3 kB/s eta 0:00:45
    --------------------------------------- 0.6/27.5 MB 624.6 kB/s eta 0:00:44
    --------------------------------------- 0.7/27.5 MB 625.9 kB/s eta 0:00:43
    --------------------------------------- 0.7/27.5 MB 626.4 kB/s eta 0:00:43
   - -------------------------------------- 0.7/27.5 MB 646.2 kB/s eta 0:00:42
   - -------------------------------------- 0.8/27.5 MB 654.9 kB/s eta 0:00:41
   - -------------------------------------- 0.8/27.5 MB 663.6 kB/s eta 0:00:41
   - -------------------------------------- 0.9/27.5 MB 663.0 kB/s eta 0:00:41
   - -------------------------------------- 0.9/27.5 MB 678.5 kB/s eta 0:00:40
   - -------------------------------------- 0.9/27.5 MB 662.6 kB/s eta 0:00:41
   - -------------------------------------- 0.9/27.5 MB 662.5 kB/s eta 0:00:41
   - -------------------------------------- 1.0/27.5 MB 662.3 kB/s eta 0:00:41
   - -------------------------------------- 1.0/27.5 MB 662.0 kB/s eta 0:00:41
   - -------------------------------------- 1.0/27.5 MB 655.0 kB/s eta 0:00:41
   - -------------------------------------- 1.0/27.5 MB 661.7 kB/s eta 0:00:41
   - -------------------------------------- 1.1/27.5 MB 668.0 kB/s eta 0:00:40
   - -------------------------------------- 1.1/27.5 MB 667.6 kB/s eta 0:00:40
   - -------------------------------------- 1.1/27.5 MB 661.0 kB/s eta 0:00:40
   - -------------------------------------- 1.2/27.5 MB 661.0 kB/s eta 0:00:40
   - -------------------------------------- 1.2/27.5 MB 672.3 kB/s eta 0:00:40
   - -------------------------------------- 1.2/27.5 MB 671.8 kB/s eta 0:00:40
   - -------------------------------------- 1.3/27.5 MB 671.7 kB/s eta 0:00:40
   - -------------------------------------- 1.3/27.5 MB 676.6 kB/s eta 0:00:39
   - -------------------------------------- 1.3/27.5 MB 676.0 kB/s eta 0:00:39
   - -------------------------------------- 1.4/27.5 MB 675.6 kB/s eta 0:00:39
   -- ------------------------------------- 1.4/27.5 MB 670.3 kB/s eta 0:00:40
   -- ------------------------------------- 1.4/27.5 MB 674.8 kB/s eta 0:00:39
   -- ------------------------------------- 1.5/27.5 MB 679.5 kB/s eta 0:00:39
   -- ------------------------------------- 1.5/27.5 MB 673.9 kB/s eta 0:00:39
   -- ------------------------------------- 1.5/27.5 MB 673.7 kB/s eta 0:00:39
   -- ------------------------------------- 1.5/27.5 MB 673.3 kB/s eta 0:00:39
   -- ------------------------------------- 1.5/27.5 MB 668.7 kB/s eta 0:00:39
   -- ------------------------------------- 1.6/27.5 MB 668.3 kB/s eta 0:00:39
   -- ------------------------------------- 1.6/27.5 MB 663.8 kB/s eta 0:00:40
   -- ------------------------------------- 1.6/27.5 MB 663.6 kB/s eta 0:00:40
   -- ------------------------------------- 1.7/27.5 MB 667.7 kB/s eta 0:00:39
   -- ------------------------------------- 1.7/27.5 MB 667.6 kB/s eta 0:00:39
   -- ------------------------------------- 1.7/27.5 MB 663.2 kB/s eta 0:00:39
   -- ------------------------------------- 1.7/27.5 MB 663.0 kB/s eta 0:00:39
   -- ------------------------------------- 1.8/27.5 MB 666.7 kB/s eta 0:00:39
   -- ------------------------------------- 1.8/27.5 MB 666.5 kB/s eta 0:00:39
   -- ------------------------------------- 1.8/27.5 MB 666.5 kB/s eta 0:00:39
   -- ------------------------------------- 1.8/27.5 MB 658.9 kB/s eta 0:00:39
   -- ------------------------------------- 1.9/27.5 MB 658.8 kB/s eta 0:00:39
   -- ------------------------------------- 1.9/27.5 MB 655.4 kB/s eta 0:00:40
   -- ------------------------------------- 1.9/27.5 MB 655.3 kB/s eta 0:00:40

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install pandas
%pip install seaborn

Requirement already satisfied: pandas in c:\users\usuario\ciai\venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\usuario\ciai\venv\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\ciai\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\usuario\ciai\venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\usuario\ciai\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\usuario\ciai\venv\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\usuario\ciai\venv\lib\site-packages (from seaborn) (2.4.3)
Requirement already satisfied: pandas>=1.2 in c:\users\usuario\ciai\venv\lib\site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\usuario\ciai\venv\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\usuario\ciai\venv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\usuario\ciai\venv\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\usuario\ciai\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Recupero el conjutno completo de datos: https://huggingface.co/datasets/piuba-bigdata/articles_and_comments

In [3]:
%pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Requirement already satisfied: python-dotenv in c:\users\usuario\ciai\venv\lib\site-packages (from dotenv) (1.2.2)
Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: dotenv
Successfully installed dotenv-0.9.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import os
from dotenv import load_dotenv
from datasets import load_dataset
import pandas as pd

load_dotenv() 
token = os.getenv("HF_TOKEN")


dataset = load_dataset("piubamas/articles_and_comments", token=token)

README.md: 0.00B [00:00, ?B/s]

c:\Users\Usuario\CIAI\venv\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Usuario\.cache\huggingface\hub\datasets--piubamas--articles_and_comments. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

data/train-00000-of-00009-29bba7769978a8(…):   0%|          | 0.00/189M [00:00<?, ?B/s]

data/train-00001-of-00009-f77652b4ff9787(…):   0%|          | 0.00/206M [00:00<?, ?B/s]

data/train-00002-of-00009-41e3c38299f2a6(…):   0%|          | 0.00/223M [00:00<?, ?B/s]

data/train-00003-of-00009-cfe49465c31617(…):   0%|          | 0.00/233M [00:00<?, ?B/s]

data/train-00004-of-00009-759d6d1b56b6aa(…):   0%|          | 0.00/256M [00:00<?, ?B/s]

data/train-00005-of-00009-f78558ab08b838(…):   0%|          | 0.00/242M [00:00<?, ?B/s]

data/train-00006-of-00009-d487e5f3a87022(…):   0%|          | 0.00/218M [00:00<?, ?B/s]

data/train-00007-of-00009-6bd22a1792eb5d(…):   0%|          | 0.00/225M [00:00<?, ?B/s]

data/train-00008-of-00009-489ed5a2622be5(…):   0%|          | 0.00/193M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/537201 [00:00<?, ? examples/s]

In [5]:
#from datasets import load_dataset
#import pandas as pd

#dataset = load_dataset("piubamas/articles_and_comments")

In [5]:
dataset

DatasetDict({
    train: Dataset({
        features: ['tweet_id', 'text', 'title', 'url', 'user', 'body', 'created_at', 'comments'],
        num_rows: 537201
    })
})

In [6]:
ds1 = dataset["train"]

Ejemplo de una fila

In [7]:
ds1[122]

{'tweet_id': '1376979520729849858',
 'text': 'Una fuerte apuesta a la rueda de la agroindustrialización argentina https://t.co/1o6ThCdtxw https://t.co/TLfGhLBjHu',
 'title': 'Una fuerte apuesta a la rueda de la agroindustrialización argentina',
 'url': 'https://www.lanacion.com.ar/economia/campo/una-fuerte-apuesta-a-la-rueda-de-la-agroindustrializacion-argentina-nid30032021/?utm_term=Autofeed&utm_medium=Echobox&utm_source=Twitter#Echobox=1617130198',
 'user': 'LANACION',
 'body': 'Desde el primer día, YPF Agro se propuso proveer al campo argentino de los insumos y las energías necesarias para producir más y mejor, en un contexto donde la demanda de alimentos para la población mundial sigue creciendo.\n\nEl negocio de agro de YPF cerró 2020 con ventas mayores a 1.428 millones de dólares y más de 1,5 millones de toneladas de grano canjeadas, y apuesta a incrementar estos resultados en 2021.\n\nEn ese sentido, lanzó su nueva campaña de comunicación orientada a reforzar la idea de circularidad de la actividad agrícola, después del relanzamiento de la marca en 2019.\n\nDe esta manera, la división Agro de la petrolera nacional continúa desafiando al mercado con su nuevo posicionamiento a través de soluciones integrales e innovadoras y acompaña al campo argentino en cada momento del ciclo productivo.\n\nLa producción agroindustrial alcanza a todos los lugares en todos momentos y eso es lo que transmite el nuevo comercial de YPF Agro que se suma en cualquier punto del ciclo para acompañar este proceso de producción.\n\nEn este punto, el foco está puesto en resaltar la gama de productos que la compañía tiene para ofrecer al mercado argentino:\n\nProtección de cultivos: YPF Agro refuerza la importancia del cuidado de los cultivos y destaca su atributo de calidad en fitosanitarios para dar solución a las distintas problemáticas de acuerdo con las regiones y cultivos.\n\nYPF Agro refuerza la importancia del cuidado de los cultivos y destaca su atributo de calidad en fitosanitarios para dar solución a las distintas problemáticas de acuerdo con las regiones y cultivos. Portfolio Semillas: A partir de la alianza estratégica con la marca ILLINOIS de probada trayectoria, competitividad y calidad, la tecnología disponible en semillas de YPF para todo el país se refuerza.\n\nA partir de la alianza estratégica con la marca ILLINOIS de probada trayectoria, competitividad y calidad, la tecnología disponible en semillas de YPF para todo el país se refuerza. Nutrición integral: El servicio de nutrición integral potencia el rinde con Summa Mix, una marca desarrollada para implementar mezclas a medida que se ajusten a la necesidad de cada ambiente productivo.\n\nEl servicio de nutrición integral potencia el rinde con Summa Mix, una marca desarrollada para implementar mezclas a medida que se ajusten a la necesidad de cada ambiente productivo. Sustento & Energía: Refuerza la trayectoria de la marca en combustibles y lubricantes de máxima calidad con un diferencial de llegada a la tranquera en todo el país. Esto permite poner en movimiento el ciclo de cada campaña agrícola y potenciar el rinde del cultivo.\n\nYPF Agro se consolida como referente en la industria Twitter\n\nYPF Agro, veinte años de trayectoria\n\nCon más de 20 años de experiencia, YPF Agro sigue transformando el trabajo del agricultor argentino y asegura su presencia en todo el país con más de 100 centros de distribución.\n\nAdemás de los cuatro pilares de su portfolio, YPF Agro provee bolsas silo para el almacenaje de granos, el canje de granos como herramienta de pago y servicios de asesoramiento integral.\n\nNuevo canje de granos para la cosecha gruesa\n\nPara acompañar este lanzamiento, cercano al inicio de la cosecha gruesa, YPF Agro lanza una nueva edición de su exitoso canje de granos.\n\nLos productores podrán canjear sus granos de soja y maíz recibiendo un plus de hasta 14 dólares por tonelada y acceder con grandes beneficios a la compra de insumos en protección, nutrición y combustibles. Para más información pueden visitar el sitio de YPF Agro.\n\nDe este modo, YPF Agro se consolida como referente en la industria y contribuye con el desarrollo del sector.\n\n________________________________________________________\n\nContent LAB es la unidad de generación de ideas y contenidos de LA NACION para las marcas con distribución en sus plataformas digitales y redes sociales. Este contenido fue producido para un anunciante y publicado por el Content LAB. La redacción de LA NACION no estuvo involucrada en la generación de este contenido.',
 'created_at': '2021-03-30T19:27:55Z',
 'comments': [{'created_at': '2021-03-30T21:24:03Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@LANACION basta de agroquimicos ! el futuro es la alimentation organica y el respeto de la naturaleza',
   'tweet_id': '1377008748242345986',
   'user_id': '2366473882'},
  {'created_at': '2021-03-30T23:14:41Z',
   'prediction': {'APPEARANCE': 0,
    'CALLS': 0,
    'CLASS': 0,
    'CRIMINAL': 0,
    'DISABLED': 0,
    'LGBTI': 0,
    'POLITICS': 0,
    'RACISM': 0,
    'WOMEN': 0},
   'text': '@LANACION Buenas Tardes.e dejado Notificaciones de mis denuncias .y los medios me https://t.co/l6B7tyVVV3 voy a permitir más k me amenazan cn mi pobre vida y https://t.co/Wws6czclV9 la dueña..Nadie puede ha ser política cn mis derechos.',
   'tweet_id': '1377036587750547456',
   'user_id': '1374092858228142081'}]}

En este conjunto de datos tengo las etiquetas de la clasificación realizada con el modelo BETO:

https://huggingface.co/piuba-bigdata/beto-contextualized-hate-speech

Puede usarse para comparar pero en principio nos interesa recuperar los comentarios completos para aplicarle el clasificador seleccionado

In [8]:
from datetime import datetime, timedelta
from tqdm.auto import tqdm
from collections import Counter

In [9]:
tweets_arg = []

for noticia in tqdm(dataset['train']):

    date_noticia = noticia["created_at"]
    # Convertimos la fecha de la noticia a un objeto de python
    datenoticia = datetime.strptime(date_noticia, "%Y-%m-%dT%H:%M:%S%fZ")
    i=0
    for comment in noticia["comments"]:
        date_comment = comment["created_at"]
        # Convertimos la fecha del comentario a un objeto de python
        datecomment = datetime.strptime(date_comment, "%Y-%m-%dT%H:%M:%S%fZ")
        # anexa comentarios de diarios argentinos
        tweets_arg.append({"id":i,
            "tweet_id_noticia": noticia["tweet_id"],
            "title": noticia["title"],
            "resumen": noticia["text"],
            "medio": noticia["user"],
            "date_tweet": datecomment,
            "text": comment["text"],
            "user_id": comment["user_id"],
            "CALLS":comment["prediction"]["CALLS"],
            "WOMEN":comment["prediction"]["WOMEN"],
            "LGBTI":comment["prediction"]["LGBTI"],
            "RACISM":comment["prediction"]["RACISM"],
            "CLASS":comment["prediction"]["CLASS"],
            "POLITICS":comment["prediction"]["POLITICS"],
            "DISABLED":comment["prediction"]["DISABLED"],
            "APPEARANCE":comment["prediction"]["APPEARANCE"],
            "CRIMINAL":comment["prediction"]["CRIMINAL"]
            })
        i=i+1

  0%|          | 0/537201 [00:00<?, ?it/s]

In [10]:
tweets_arg[11]

{'id': 3,
 'tweet_id_noticia': '1376940852011020288',
 'title': 'La desgarradora confesión de Hugo Maradona: “Lo sueño a Diego hablándome”',
 'resumen': 'La desgarradora confesión de Hugo Maradona: “Lo sueño a Diego hablándome” https://t.co/KKpQIYx9gD https://t.co/GN2kt809cl',
 'medio': 'LANACION',
 'date_tweet': datetime.datetime(2021, 3, 30, 17, 49, 1, 500000),
 'text': '@LANACION Re largo el sueño',
 'user_id': '395054756',
 'CALLS': 0,
 'WOMEN': 0,
 'LGBTI': 0,
 'RACISM': 0,
 'CLASS': 0,
 'POLITICS': 0,
 'DISABLED': 0,
 'APPEARANCE': 0,
 'CRIMINAL': 0}

In [11]:
# prompt: create a dataframe from tweets_arg

df_tweets_arg = pd.DataFrame(tweets_arg)

In [12]:
df_tweets_arg['HATEFUL']= df_tweets_arg[['CALLS','WOMEN','LGBTI','RACISM','CLASS','POLITICS','DISABLED','APPEARANCE','CRIMINAL']].max(axis=1)

In [13]:
df_tweets_arg.head()

,id,tweet_id_noticia,title,resumen,medio,date_tweet,text,user_id,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL,HATEFUL
0,0,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:03:00.900,@clarincom A mi me preocupa el trabajo.. La ev...,1532596098,0,0,0,0,0,0,0,0,0,0
1,1,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:05:04.500,@clarincom Lo que preocupa. https://t.co/Vmf9V...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
2,2,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:06:03.100,@clarincom Lo que les preocupa. https://t.co/P...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
3,3,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:11:02.300,@clarincom Le recomendaríamos al presidente de...,582286194,0,0,0,0,0,0,0,0,0,0
4,4,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:26:00.600,@clarincom Para salvar al correo de la quiebra...,951552761988034560,0,0,0,0,0,0,0,0,0,0

coloco el mismo orden de las etiquetas que usa el clasificador

In [14]:
# prompt: change the order of columns of df_tweets_arg and put HATEFUL before CALLS


df_tweets_arg = df_tweets_arg[['id', 'tweet_id_noticia','title','resumen','medio', 'date_tweet', 'text', 'user_id', 'HATEFUL', 'CALLS', 'WOMEN',
       'LGBTI', 'RACISM', 'CLASS', 'POLITICS', 'DISABLED', 'APPEARANCE',
       'CRIMINAL']]
df_tweets_arg.head()

,id,tweet_id_noticia,title,resumen,medio,date_tweet,text,user_id,HATEFUL,CALLS,WOMEN,LGBTI,RACISM,CLASS,POLITICS,DISABLED,APPEARANCE,CRIMINAL
0,0,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:03:00.900,@clarincom A mi me preocupa el trabajo.. La ev...,1532596098,0,0,0,0,0,0,0,0,0,0
1,1,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:05:04.500,@clarincom Lo que preocupa. https://t.co/Vmf9V...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
2,2,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:06:03.100,@clarincom Lo que les preocupa. https://t.co/P...,1222094021687943168,0,0,0,0,0,0,0,0,0,0
3,3,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:11:02.300,@clarincom Le recomendaríamos al presidente de...,582286194,0,0,0,0,0,0,0,0,0,0
4,4,1376940813968609288,Segunda ola de coronavirus: preocupan las reun...,Segunda ola de coronavirus: preocupan las reun...,clarincom,2021-03-30 17:26:00.600,@clarincom Para salvar al correo de la quiebra...,951552761988034560,0,0,0,0,0,0,0,0,0,0

In [16]:
# prompt: save df_tweets_arg to csv file

df_tweets_arg.to_csv('data/tweets_con_noticia.csv', index=False)

In [17]:
# prompt: len of df_tweets_arg

len(df_tweets_arg)

8569648